### ISSUE TITLE
找不到或无法加载主类 fun.codec.friday.starter.Controller

### ISSUE THREAD

**Issue by bingyun84** [zifeihan/friday#4]
错误: 找不到或无法加载主类 fun.codec.friday.starter.Controller    windows下执行报这个错是怎么回事？

**Comment by zifeihan** [comment]
> 错误: 找不到或无法加载主类 fun.codec.friday.starter.Controller windows下执行报这个错是怎么回事？

你好，请问你是自己修改的启动脚本支持windows吗？麻烦你把脚本内容也贴一下？晚点我找个windows测试一下。

**Comment by bingyun84** [comment]
你好，我的脚本windos下是可以执行的，就把APP_HOME=D:\\friday-starter路径改了一下，后面是启动的脚本，麻烦您帮忙看看，谢谢！

#!/bin/sh
cd `pwd`

STR=`jps -l | grep "fun.codec.friday.starter.Controller" | awk  -F ' '  '{print $1}'`
if [ ! -z "$STR" ]; then
    kill -9 $STR > /dev/null 2>&1
    sleep 2
else
  echo "没有Java进程"
fi

APP_HOME=D:\\friday-starter

echo "app.path : ${APP_HOME}"

echo "APP_HOME:"${APP_HOME}
DIR_LOG=${APP_HOME}/logs

if [ ! -e $DIR_LOG ] ; then
    mkdir -p $DIR_LOG
fi

FILE_STDOUT_LOG=$DIR_LOG/stdout.log
FILE_STDERR_LOG=$DIR_LOG/stderr.log

DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=28004,server=y,suspend=n"

java $DEBUG_OPTS \
-Dapp.home=${APP_HOME} \
D:\\friday-starter\\lib\\friday-starter.jar > ${FILE_STDOUT_LOG} 2>${FILE_STDERR_LOG} &

**Comment by zifeihan** [comment]
> 你好，我的脚本windos下是可以执行的，就把APP_HOME=D:\friday-starter路径改了一下，后面是启动的脚本，麻烦您帮忙看看，谢谢！
> 
> #!/bin/sh
> cd `pwd`
> 
> STR=`jps -l | grep "fun.codec.friday.starter.Controller" | awk -F ' ' '{print $1}'`
> if [ ! -z "$STR" ]; then
> kill -9 $STR > /dev/null 2>&1
> sleep 2
> else
> echo "没有Java进程"
> fi
> 
> APP_HOME=D:\friday-starter
> 
> echo "app.path : ${APP_HOME}"
> 
> echo "APP_HOME:"${APP_HOME}
> DIR_LOG=${APP_HOME}/logs
> 
> if [ ! -e $DIR_LOG ] ; then
> mkdir -p $DIR_LOG
> fi
> 
> FILE_STDOUT_LOG=$DIR_LOG/stdout.log
> FILE_STDERR_LOG=$DIR_LOG/stderr.log
> 
> DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=28004,server=y,suspend=n"
> 
> java $DEBUG_OPTS
> -Dapp.home=${APP_HOME}
> D:\friday-starter\lib\friday-starter.jar > ${FILE_STDOUT_LOG} 2>${FILE_STDERR_LOG} &

你好，我看了一下你提供的这个脚本，有个问题，在原本这个脚本里面在java后面应该有个-cp "${APP_HOME}/lib/*:${JAVA_HOME}/lib/*"，这个是classpath，如果缺少classpath是会出现这个问题。或者你可以把代码下载到本地，用idea启动一下，在idea里面不用配置任何东西，导入启动fun.codec.friday.starter.Controller就可以。

**Comment by bingyun84** [comment]
你好，我之前是把包拷贝到${JAVA_HOME}/lib/,加上也是同样报错,用idea可以起来了,能显示程序和左侧的列表,但点某一个类的时候会报错,反射不出来代码,没看到有生成.class文件,具体报错:
Can't load the class specified:
org.benf.cfr.reader.util.CannotLoadClassException: C:\Users\Administrator\friday\20720\class\Users\Administrator\friday\20720\dir\com\lightinit\PftApplication.class - java.io.IOException: No such file C:\Users\Administrator\friday\20720\class\Users\Administrator\friday\20720\dir\com\lightinit\PftApplication.class
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException

**Comment by zifeihan** [comment]
> 你好，我之前是把包拷贝到${JAVA_HOME}/lib/,加上也是同样报错,用idea可以起来了,能显示程序和左侧的列表,但点某一个类的时候会报错,反射不出来代码,没看到有生成.class文件,具体报错:
> Can't load the class specified:
> org.benf.cfr.reader.util.CannotLoadClassException: C:\Users\Administrator\friday\20720\class\Users\Administrator\friday\20720\dir\com\lightinit\PftApplication.class - java.io.IOException: No such file C:\Users\Administrator\friday\20720\class\Users\Administrator\friday\20720\dir\com\lightinit\PftApplication.class
> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException

收到，我晚点测试一下。

**Comment by bingyun84** [comment]
请问下是启动需要加什么参数么？

**Comment by zifeihan** [comment]
不好意思，最近太忙了。已修复，你可以拉取最新代码，在idea里面运行即可。windows我不太熟悉，没有提供启动脚本，要是你感兴趣的话，可以尝试提供windows启动脚本，然后提交pr合并，让更多的人使用方便。
![image](https://user-images.githubusercontent.com/16839929/102083397-72d70f00-3e4e-11eb-9e33-de342e7e6d27.png)
